version: '3.8'
services:
  api:
    build: .
    depends_on:
      - db
    ports:
     - "8000:80"
    volumes:
     - .:/app
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/postgresdb
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgresdb
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
volumes:
  postgres_data:
